### PR TITLE
feat: MON-13253 standardization of invalid license messages

### PR DESCRIPTION
**Pull request by JKancel**
## Description

This PR introduced a new background template svg component to style error pages :

https://user-images.githubusercontent.com/6154460/189327166-bb6d329a-3957-49a0-acc2-5d4708ef8ba4.mov

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [x] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

- Go to `centreon-ui` folder,
- Launch storybook with the following command : ``` npm run storybook ```
- Navigate to [navigate to your local storybook instance](http://localhost:9001/?path=/story/fallbackpage-licenceinvalid--licence-invalid)
- Try the fallback page by editing its props.

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

### CODE REVIEW

**Review by Thebarda — COMMENTED** [review]
Is it possible to use real assets instead of "plain svg" components

**Comment by bdauria** [comment]
@JKancel the visual tests seem to fail. We might have to update the snapshots

**Comment by JKancel** [comment]
> Details

@bdauria Snapshots were updated, but it looks like there some missing .xml :
Screenshot 2022-09-12 at 09 46 21

**Comment by Thebarda** [comment]
> > Details
> 
> @bdauria Snapshots were updated, but it looks like there some missing .xml : Screenshot 2022-09-12 at 09 46 21

Rebuild the CI then

**Comment by JKancel** [comment]
Replaced by https://github.com/centreon/centreon-frontend/pull/205

**Pull request closed without merging**
