### PR TITLE
enh(StatusChip): update style of statusChip

### PR DESCRIPTION
**Pull request by Noha-ElAbrouki**
put color for status of type low to white

### CODE REVIEW

**Review by Thebarda — APPROVED** [review]
Is it possible to update snapshots please?

**Comment by bdauria** [comment]
@Noha-ElAbrouki You might want to re-generate the snapshots to update them. You can do so by running (in the centreon-ui directory):
```
npm t -- -u
```

Please check if the contrast ratio passes by using: https://colourcontrast.cc/6bffc8/222222
otherwise, we might want to adjust the colors

**Review by Jordan91 — APPROVED** [review]

**Review by bdauria — CHANGES_REQUESTED** [review]
See comments above

**Review by Jordan91 — COMMENTED** [review]
You have lot of issues on storyshot ,without fix you'll can't merge your PR.

**Review by Thebarda — APPROVED** [review]

**Review by Jordan91 — APPROVED** [review]

**Review by bdauria — APPROVED** [review]

**Pull request merged**
